version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(gha):"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps):"
    groups:
      build:
        patterns:
          - "@existdb/*"
          - "gulp*"
          - "delete"
          - "dotenv-cli"
      release:
        patterns:
          - "@semantic-release/*"
          - "semantic-release"
      test:
        patterns:
          - "form-data"
          - "axios"
          - "chai"
          - "jsdom"
          - "mocha"
